#!/usr/bin/env bash
#
# IG cookie export wizard: walks a human through exporting their Instagram
# session cookies from the browser, writes them into sources.json, and
# generates COOKIES-GUIDE.md explaining how to get the cookie information.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

DOC_FILE="COOKIES-GUIDE.md"
SOURCES_FILE="${SOURCES_FILE:-sources.json}"
SOURCE_ID="${SOURCE_ID:-ig-primary}"
SOURCE_NAME="Primary Instagram"

# Always operate inside the repo the wizard lives in.
cd "$(dirname "${BASH_SOURCE[0]}")"

# ── helpers (wizard-specific, kept below the marker) ──────────────────────

# _cookie_value NAME — current value of cookie NAME on $SOURCE_ID, if any.
_cookie_value() {
  node -e '
    const fs = require("fs");
    try {
      const data = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      const src = (data.sources || []).find(s => s && s.id === process.argv[2]);
      const c = src && (src.cookies || []).find(c => c.name === process.argv[3]);
      if (c && c.value && !/YOUR_[A-Z_]*HERE/.test(c.value)) process.stdout.write(c.value);
    } catch (_) {}
  ' "$SOURCES_FILE" "$SOURCE_ID" "$1"
}

# ask_cookie KEY COOKIE "Prompt" — visible entry, keeps current value on re-run.
ask_cookie() {
  local key="$1" cookie="$2" prompt="$3" current input
  current=$(_cookie_value "$cookie")
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_cookie_secret KEY COOKIE "Prompt" — hidden entry for the session token.
ask_cookie_secret() {
  local key="$1" cookie="$2" prompt="$3" current input
  current=$(_cookie_value "$cookie")
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# _valid_cookie VALUE — rejects empty input or a leftover placeholder.
_valid_cookie() {
  [[ -n "$1" ]] && [[ "$1" != *YOUR_*HERE* ]] && [[ "$1" != *" "* ]]
}

# ── stages ────────────────────────────────────────────────────────────────

banner "IG cookie export → sources.json + how-to guide"

stage "Prerequisites"
say "This wizard captures your Instagram session cookies and stores them in"
say "$SOURCES_FILE → source '$SOURCE_ID' ($SOURCE_NAME), then generates $DOC_FILE."
note "You need: a desktop browser on this machine where you are logged in to"
note "Instagram. No terminal skills required beyond copy & paste."
warn "sessionid is your full login credential: it is entered hidden, and"
warn "sources.json is gitignored. Never paste it into chats, issues, or commits."
pause "Press Enter when you are ready."

stage "Open Instagram (logged in)"
say "First we confirm your browser session is active before copying cookies."
open_url "https://www.instagram.com/"
step "If you see a login form instead of your feed, log in now."
step "Your feed should load with posts — that means the session is valid."
pause "Press Enter once your feed is visible (you are logged in)."

stage "DevTools → Cookies"
say "Instagram hides its cookies in the browser developer tools:"
step "Chrome / Edge: press F12 → click the 'Application' tab (top bar; may be"
note "   under the '>>' overflow menu)."
step "Firefox: press F12 → click the 'Storage' tab."
step "Left sidebar: expand 'Cookies' → click 'https://www.instagram.com'."
step "Use the Filter box at the top of the table to type a cookie name."
note "You will see rows like sessionid, ds_user_id, csrftoken, ig_did, mid, rur."
pause "Press Enter once the cookie table for instagram.com is visible."

stage "Capture sessionid"
say "sessionid is the value that authenticates you — it is entered hidden."
step "In the cookie table, click the row named 'sessionid'."
step "Copy its 'Value' cell (a long token, ~30+ chars, letters and digits)."
ask_cookie_secret SESSION_ID sessionid "Paste the sessionid value:"
if ! _valid_cookie "$SESSION_ID"; then
  warn "That does not look like a sessionid — it must be a long token with no spaces."
  ask_cookie_secret SESSION_ID sessionid "Paste the sessionid value again:"
fi

stage "Capture ds_user_id"
say "ds_user_id is your numeric Instagram user ID."
step "In the cookie table, click the row named 'ds_user_id'."
step "Copy its 'Value' cell (a number, usually 8–12 digits)."
ask_cookie DS_USER_ID ds_user_id "Paste the ds_user_id value:"
if ! _valid_cookie "$DS_USER_ID"; then
  warn "That does not look like a user ID — it should be digits only."
  ask_cookie DS_USER_ID ds_user_id "Paste the ds_user_id value again:"
fi

stage "Capture csrftoken"
say "csrftoken is the CSRF token paired with your session."
step "In the cookie table, click the row named 'csrftoken'."
step "Copy its 'Value' cell (32 hex-like characters)."
ask_cookie CSRF_TOKEN csrftoken "Paste the csrftoken value:"
if ! _valid_cookie "$CSRF_TOKEN"; then
  warn "That does not look like a csrftoken — it should be ~32 hex characters."
  ask_cookie CSRF_TOKEN csrftoken "Paste the csrftoken value again:"
fi

stage "Write cookies into sources.json"
say "The wizard will replace the cookies of source '$SOURCE_ID' ($SOURCE_NAME):"
note "  • sessionid   = •••• (hidden, not echoed)"
note "  • ds_user_id  = $DS_USER_ID"
note "  • csrftoken   = $CSRF_TOKEN"
note "Any other cookies already present (mid, ig_did, rur, ...) are kept."
note "A timestamped backup of $SOURCES_FILE is created first."
if confirm "Replace the cookies for '$SOURCE_ID' in $SOURCES_FILE"; then
  if [[ -f "$SOURCES_FILE" ]]; then
    cp "$SOURCES_FILE" "$SOURCES_FILE.bak-$(date +%Y%m%d-%H%M%S)"
  fi
  SESSION_ID="$SESSION_ID" DS_USER_ID="$DS_USER_ID" CSRF_TOKEN="$CSRF_TOKEN" \
    node -e '
      const fs = require("fs");
      const file = process.argv[1], id = process.argv[2];
      let data = { sources: [] };
      try { data = JSON.parse(fs.readFileSync(file, "utf8")); } catch (_) {}
      const fresh = [
        { name: "sessionid",   value: process.env.SESSION_ID,  domain: ".instagram.com", path: "/", secure: true,  httpOnly: true,  sameSite: "Lax" },
        { name: "ds_user_id",  value: process.env.DS_USER_ID,  domain: ".instagram.com", path: "/", secure: true,  httpOnly: false, sameSite: "Lax" },
        { name: "csrftoken",   value: process.env.CSRF_TOKEN,  domain: ".instagram.com", path: "/", secure: true,  httpOnly: true,  sameSite: "Lax" },
      ];
      const srcs = Array.isArray(data.sources) ? data.sources : [];
      const idx = srcs.findIndex(s => s && s.id === id);
      const existing = idx >= 0 && Array.isArray(srcs[idx].cookies) ? srcs[idx].cookies : [];
      const kept = existing.filter(c => c && c.name && !fresh.some(f => f.name === c.name));
      const merged = fresh.concat(kept);
      if (idx >= 0) srcs[idx] = { ...srcs[idx], cookies: merged, updatedAt: new Date().toISOString() };
      else srcs.push({ id, name: "Primary Instagram", type: "instagram", enabled: true, cookies: merged, updatedAt: new Date().toISOString() });
      data.sources = srcs;
      fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n");
      console.log("  ✓ wrote " + merged.length + " cookies (" + fresh.length + " refreshed) to " + file + " → " + id);
    ' "$SOURCES_FILE" "$SOURCE_ID"
  DOC_STATUS="sources.json updated (sessionid, ds_user_id, csrftoken)"
else
  DOC_STATUS="sources.json NOT updated — you declined the write"
  SKIPPED+=("sources.json update (declined this run)")
  warn "skipped writing sources.json — the cookies captured this run were not saved"
fi

stage "Generate the how-to document"
say "Writing $DOC_FILE — the full walkthrough of how to get your IG cookie info."
cat > "$DOC_FILE" <<EOF
# How to Get Your Instagram Cookie Information

This guide explains how to obtain the Instagram session cookies used by the
IG Feed Watcher (\`watcher.js\`) and the Posting API (\`post-server.js\`), how to
store them, when to refresh them, and how to stay safe with them.

> Generated by \`./get-ig-cookies.sh\` — run that wizard again whenever your
> session expires; it walks you through this process interactively and writes
> the cookies into \`sources.json\` for you.

## What you need and why

| Cookie | What it is | Sensitivity |
| --- | --- | --- |
| \`sessionid\` | Your login session token — the credential that proves you are you. | 🔴 Treat as a password: full account access. |
| \`ds_user_id\` | Your numeric Instagram user ID. | 🟡 Private-ish; identifies your account. |
| \`csrftoken\` | CSRF token paired with the session, sent with every request. | 🟡 Sensitive; rotates with the session. |
| \`mid\`, \`ig_did\`, \`rur\` | Device / region cookies; optional but Instagram may ask for them. | 🟢 Low sensitivity. |

\`sessionid\` alone is enough to take over an account: anyone holding it can read
your DMs, post as you, and change your password. Keep it out of chats, issues,
commits, and screenshots.

## Where the cookies live in this repo

- \`sources.json\` → source \`ig-primary\` ("Primary Instagram") — the **active**
  config. One entry per account, each with its own \`cookies\` array.
- \`cookies.json\` — the **legacy single-account** fallback, used only when
  \`sources.json\` is absent.
- Both files are listed in \`.gitignore\` and must never be committed.

Cookie entry format (Puppeteer / DevTools shape):

\`\`\`json
{
  "name": "sessionid",
  "value": "YOUR_SESSION_ID",
  "domain": ".instagram.com",
  "path": "/",
  "secure": true,
  "httpOnly": true,
  "sameSite": "Lax"
}
\`\`\`

## The recommended way: run the wizard

\`\`\`bash
cd /home/bsdev/ig-feed-watcher
./get-ig-cookies.sh
\`\`\`

It opens Instagram, walks you through DevTools, captures the three cookies
(\`sessionid\` is entered hidden), backs up and updates \`sources.json\`, and
writes this guide.

## The manual way (step by step)

1. Open \`https://www.instagram.com/\` in your desktop browser and **log in**.
2. Press \`F12\` to open DevTools.
3. Chrome / Edge: open the **Application** tab. Firefox: open the **Storage** tab.
4. In the left sidebar expand **Cookies** and click \`https://www.instagram.com\`.
5. Use the **Filter** box to find each cookie by name.
6. For each cookie below, click the row and copy the **Value** cell:

| Order | Cookie | Looks like |
| --- | --- | --- |
| 1 | \`sessionid\` | long alphanumeric token (~30+ chars) |
| 2 | \`ds_user_id\` | a number (your user ID) |
| 3 | \`csrftoken\` | 32 hex-like characters |

7. Paste the values where they belong:
   - into the wizard (\`./get-ig-cookies.sh\`), or
   - into the Web Explorer settings page (🔑 Sources), or
   - by hand into \`sources.json\` / \`cookies.json\` (format above).

## Verify the cookies work

\`\`\`bash
node watcher.js
# posting API status:
node post-server.js   # then: curl -s http://localhost:4030/status
\`\`\`

\`GET /api/sources\` (server.js, port 4180) lists cookie names per source with
values masked — a safe way to confirm which cookies are configured.

## Refresh when the session expires

Instagram rotates sessions — expect to re-export every few weeks. Symptoms:

- the watcher logs \`login required\`, \`challenge\`, or 401 responses;
- the feed comes back empty or redirects to the login page;
- posting fails with a login / challenge error.

Fix: re-run \`./get-ig-cookies.sh\`. The wizard keeps other cookies (e.g. \`mid\`,
\`ig_did\`) and only replaces \`sessionid\`, \`ds_user_id\`, \`csrftoken\`.

## Alternate export methods

| Method | Command | Needs |
| --- | --- | --- |
| Chrome profile export | \`python3 export-cookies.py\` | Local Chrome profile on this machine |
| Interactive login helper | \`node login.js\` | A display / X11 (not headless) |
| Browser extension | e.g. "Get cookies.txt LOCALLY" | Paste the exported lines into the same format |

## Security rules

- \`sessionid\` is a full login credential — never paste it into chat, issues,
  commits, or screenshots.
- \`sources.json\` and \`cookies.json\` are gitignored; if they were ever
  committed, rotate your password and remove them from git history.
- Cookies are tied to the browser/login they came from; using an export on
  another device usually works, but Instagram may flag the device/IP change.
- This project automates a real browser with your real session. Instagram can
  detect automation — use at your own risk and keep polling gentle (5–15 min).

## This run

- Generated: $(date -u '+%Y-%m-%d %H:%M UTC')
- Source updated: \`$SOURCE_ID\` ($SOURCE_NAME)
- $DOC_STATUS
- Files touched: \`$SOURCES_FILE\`, \`$DOC_FILE\`
- Next step: run \`node watcher.js\` to confirm the session works.
EOF
say "✓ $DOC_FILE written"

finish

printf '%s\n' "  Open $DOC_FILE to read the how-to at any time."
note "Re-run ./get-ig-cookies.sh whenever Instagram expires the session."
